letraA:
	python ./letras_resolucoes/letra_a.py

letraB:
	python ./letras_resolucoes/letra_b.py

letraC:
	python ./letras_resolucoes/letra_c.py

letraD:
	python ./letras_resolucoes/letra_d.py

letraE:
	python ./letras_resolucoes/letra_e.py

letraF:
	python ./letras_resolucoes/letra_f.py

letraG:
	python ./letras_resolucoes/letra_g.py