letraA:
	python ./letras_resolucoes/letra_a.py

letraB:
	python ./letras_resolucoes/letra_b.py

letraD:
	python ./letras_resolucoes/letra_d.py

letraE:
	python ./letras_resolucoes/letra_e.py

letraG:
	python ./letras_resolucoes/letra_g.py